name: Custom Diff

on:
  pull_request:
    paths:
      - '**/*.txt'
jobs:
  custom-diff:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Filenames
      run: |
        for file in $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep '.proto$'); do
           echo $file >> file_list.txt
        done
    - name: Post Comment
      if: always()
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = require('path');


          const issue_number = context.issue.number;
          const githubToken = process.env.GITHUB_TOKEN;
          //const octokit = github.getOctokit(githubToken);

          console.log(context.sha);
          console.log(issue_number);
          console.log(context.repo.repo);
          console.log(context.repo.owner);

          await github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: issue_number,
            body: "Custom Diff",
            commit_id: context.sha,
            path: '/my_testfile.txt',
            position: 1,
          });
