name: Custom Diff

on:
  pull_request:
    paths:
      - '**/*.txt'
jobs:
  custom-diff:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Filenames
      run: |
        for file in $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep '.proto$'); do
           echo $file >> file_list.txt
        done

    - name: Fetch PR commits
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/pull/${{ github.event.pull_request.number }}/head

    - name: Get PR commit hash
      id: prcommithash
      run: |
          PR_COMMIT_HASH=$(git log --format="%H" -n 1 refs/pull/${{ github.event.pull_request.number }}/head)
          echo "Latest PR Commit Hash: $PR_COMMIT_HASH"
          echo "pr_commit_hash="$PR_COMMIT_HASH >> $GITHUB_OUTPUT

    - name: Post Comment
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const issue_number = context.issue.number;
          const githubToken = process.env.GITHUB_TOKEN;

          console.log("Sha:" + context.sha);
          console.log("Issue Number:" + issue_number);
          console.log("Repo:" +context.repo.repo);
          console.log("Owner:"+context.repo.owner);

          // "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          //let files = await github.rest.pulls.files({
          //  owner: context.repo.owner,
          //  repo: context.repo.repo,
          //  pull_number: issue_number,
          //})

          //console.log(files);
          
          await github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: issue_number,
            body: "Custom Diff",
            commit_id: '${{ steps.prcommithash.outputs.pr_commit_hash }}',
            path: 'my_testfile.txt',
            // start_line: 1,
            // start_side: "RIGHT",
            line: 36,
            side: "RIGHT",
          });
